import Head from "next/head";
import Image from "next/image";
import SidebarLayout from "../comps/sidebarLayout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <SidebarLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Image
          src="/img/logo dark bg.png"
          width={500}
          height={500}
          className={styles.img}
        />
        <p className={styles.text}>We are the best!</p>
      </div>
    </SidebarLayout>
  );
}
